# Assignment 4: Data Wrangling
```
Course: ENV 700 - Environmental Data Exploration
Author: Student Name
Date: Fall 2026
```

This notebook accompanies the Python lessons on **Data Wrangling**, the second stage in the data analytics pipeline: **exploration, wrangling, analysis, and visualization**.

In this notebook, you will be working with US EPA Air Quality System (AQS) data on ozone and fine particulate matter (2.5 mm) levels recorded at its North Carolina monitoring stations for the years 2024 and 2025. The raw data files are provided as four separate CSV files: one for each pollutant-year combination. In this exercise, you will import each and wrangle them separately so that they can be combined into a single dataframe, where additional wrangling will enable comprehensive analysis of the dataset.

---
### 1. Set up your Python Session

#### ✅ 1.1 Import Packages
* Load the pathlib Path object and the Pandas package into your coding environnment

In [65]:
# 1.1 Import Packages
from pathlib import Path
import pandas as pd

#### ✅ 1.2 Set project folder variables
* Create three Path variables, one set to your project's **root folder** one set to the **raw data folder** and another to the **processed data folder**. 
* Display the the values of these three variables in your notebook.

In [66]:
# 1.2 Set project folders using relative paths
project_fldr = Path.cwd().parent
raw_fldr = project_fldr / 'data' / 'raw'
processed_fldr = project_fldr / 'data' / 'processed'
raw_fldr

WindowsPath('c:/Users/ajc189/Documents/ENV700/data/raw')

#### ✅ 1.3 Set a path to the raw data files
* Create a Path variable pointing to the four EPA AQS files found in the raw data folder: 
    - `EPAair_O3_NC2024_raw.csv`
    - `EPAair_O3_NC2025_raw.csv`
    - `EPAair_PM25_NC2024_raw.csv`
    - `EPAair_PM25_NC2025_raw.csv`

In [67]:
# 1.3 Create file path variables
NC2024_path= raw_fldr / 'EPAair_O3_NC2024_raw.csv'
NC2025_path= raw_fldr /'EPAair_O3_NC2025_raw.csv'
PM25_NC2024_path = raw_fldr / 'EPAair_PM25_NC2024_raw.csv'
PM25_NC2025_path = raw_fldr / 'EPAair_PM25_NC2025_raw.csv'

#### ✅ 1.4 Read the four files into separate dataframes
(*No need to set data types, parse dates, or perform any other specialize import functions here; we will wrangle value later.*)

In [68]:
# 1.4 Read data into dataframes
NC2024 = pd.read_csv(NC2024_path)
NC2025 = pd.read_csv(NC2025_path)
PM25_NC2024 = pd.read_csv(PM25_NC2024_path)
PM25_NC2025 = pd.read_csv(PM25_NC2025_path)

#### ✅ 1.5 Report the dimensions of each dataframe
🔥***TIP***: *Each dataframe should have a different number of records.*

In [69]:
# 1.5 Report the dimensions of each dataset
print(NC2024.shape)
print(NC2025.shape)
print(PM25_NC2024.shape)
print(PM25_NC2025.shape)

(9519, 21)
(9466, 21)
(9752, 22)
(10184, 22)

---
### 2. Wrangle individual datasets

#### ✅ 2.1 Update data types
* Convert the `Date` column in each dataframe so that values are datetime objects. 
* List the date range for the two Ozone dataframes.

In [70]:
# Convert the Date column to DateTime objects
NC2024['Date'].head
NC2024['Date']= pd.to_datetime(NC2024['Date'], format='%m/%d/%Y')
NC2025['Date']= pd.to_datetime(NC2025['Date'], format='%m/%d/%Y')
PM25_NC2024['Date']= pd.to_datetime(PM25_NC2024['Date'], format='%m/%d/%Y')
PM25_NC2024['Date']= pd.to_datetime(PM25_NC2025['Date'], format='%m/%d/%Y')
# Print date ranges
print("NC2024 Date range", NC2024['Date'].min(), "to", NC2024['Date'].max())
print("NC2025 Date range", NC2025['Date'].min(), "to", NC2025['Date'].max())

NC2024 Date range 2024-01-01 00:00:00 to 2024-12-30 00:00:00
NC2025 Date range 2025-01-01 00:00:00 to 2025-12-31 00:00:00

#### ✅ 2.2 Eliminate unnecessary columns
* Subset each dataframe to include only the following columns:  
```'Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude'```

In [71]:
# 2.2 Subset columns
col_to_keep = ['Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude']
NC2024=NC2024.loc[:, col_to_keep]
NC2025=NC2025.loc[:, col_to_keep]
PM25_NC2024=PM25_NC2024.loc[:, col_to_keep]
PM25_NC2025=PM25_NC2025.loc[:, col_to_keep]

#### ✅ 2.3 Update values
* For the PM2.5 datasets, fill all cells in the `AQS Parameter Description` with the string "PM2.5".  
(*All cell values in this column will be identical.*)

In [72]:
# 2.3 Update values
PM25_NC2024.loc[:, 'AQS Parameter Description']="PM2.5"
PM25_NC2025.loc[:, 'AQS Parameter Description']="PM2.5"

---
### 3. Combine datasets

#### ✅ 3.1 Confirm dataframes are set to be merged
* Ensure that column names in each dataframe are indentical

In [73]:
# 3.1 Ensure column are same across all dataframes
print(NC2024.columns),
print(NC2025.columns),
print(PM25_NC2024.columns),
print(PM25_NC2025.columns)

Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')
Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')
Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')
Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')

#### ✅ 3.2 Combine the datasets 
* Combine the datasets using Pandas' `concat()` function
* Report the dimensions of the merged dataframe. (This should be `38,921 x 7`)

In [74]:
# 3.2 Concatentate & report shape
EPA_air_combined=pd.concat([NC2024, NC2025, PM25_NC2024, PM25_NC2025], ignore_index=True)
EPA_air_combined.shape

(38921, 7)

#### ✅ 3.3 Examine the contents of the merged dataframe
* Display a sample of 10 randomly selected rows, using the random state = 42

In [75]:
# 3.3 View a sample of data
EPA_air_combined.sample(10, random_state=42)

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
26921,2025-10-01 00:00:00,24,Pitt Agri. Center,PM2.5,Pitt,35.641276,-77.360126
6483,2024-04-22 00:00:00,40,University Meadows,Ozone,Mecklenburg,35.314158,-80.713469
34315,02/18/2025,53,Remount,PM2.5,Mecklenburg,35.213171,-80.874084
12494,2025-08-08 00:00:00,39,Clemmons Middle,Ozone,Forsyth,36.026612,-80.341962
27781,2025-03-08 00:00:00,12,Old High School,PM2.5,Swain,35.498711,-83.310242
23089,2025-11-29 00:00:00,59,Mendenhall School,PM2.5,Guilford,36.109006,-79.802314
35024,02/16/2025,27,Spruce Pine Hospital,PM2.5,Mitchell,35.912487,-82.062082
1157,2024-08-14 00:00:00,40,Beaufort,Ozone,Carteret,34.884800,-76.620300
4178,2024-09-14 00:00:00,31,Waynesville School,Ozone,Haywood,35.507224,-82.963625
13592,2025-03-29 00:00:00,45,Waynesville School,Ozone,Haywood,35.507224,-82.963625

---
### 4. Wrangle the combined dataset

#### ✅ 4.1 Subset rows 
* Generate a list of local site names common to all 4 dataframes (code provided, but replace the dataframe names to match your own).
* Create a subset of the full dataset, selecting those that match these local site names.
* Report the dimensions of the resulting dataframe. (This should be `18,778 x 7`)

In [78]:
# Generate a list of local site names common to all 4 dataframes
## Create set objects from the values in the Local Site Name columns
sites_oz24 = set(NC2024['Local Site Name']) #<-- update dataframe name to use your 2024 Ozone dataframe
sites_oz25 = set(NC2025['Local Site Name'])
sites_pm24 = set(PM25_NC2024['Local Site Name'])
sites_pm25 = set(PM25_NC2025['Local Site Name'])
## Compute the intersection 
common_sites = sites_oz24 & sites_oz25 & sites_pm24 & sites_pm25
common_sites

{'Bryson City',
 'Castle Hayne',
 'Clemmons Middle',
 'Durham Armory',
 'Frying Pan Mountain',
 'Garinger High School',
 'Hattie Avenue',
 'Leggett',
 'Linville Falls',
 'Mendenhall School',
 'Millbrook School',
 'Old High School',
 'Pitt Agri. Center',
 'Rockwell',
 'West Johnston Co.'}

In [81]:
# 4.1 Subset for records with sites in common
EPA_air_common_sites=EPA_air_combined[EPA_air_combined['Local Site Name'].isin(common_sites)]
EPA_air_common_sites.shape

(18778, 7)

#### ✅ 4.2 Group and summarize data 
We want a dataset that lists one record per measured pollutant per location per day. To ensure we have that, we'll group data by date, local site name, AQS parameter, and county, computing the mean daily AQI value as well as mean latitude and longitude value. 
* Group the data on the grouping variables mentioned above. 
* For each group, compute mean daily AQI value, mean latitude, and mean longitude. 
* Reset the index of the summarized dataset to restore the product to a flat dataframe.
* Report the dimensions of the dataset. (This should be `17,017 x 7`.)

In [90]:
# 4.2 Group and summarize data, then report its dimensions
EPA_air_group=(
    EPA_air_common_sites
    .groupby(['Date', 'Local Site Name', 'AQS Parameter Description', 'County'])
    .agg(
        mean_aqi=("Daily AQI Value", "mean"),
        mean_latitude=("Site Latitude", "mean"),
        mean_longitude=("Site Longitude", "mean"),
    )
.reset_index()
)

EPA_air_group.shape

(16760, 7)

**I can't figure out why my shape is wrong**

#### ✅ 4.3 Add calculated columns
* Add `Year` and `Month` columns to your dataframe, deriving values from the `Date` field.

In [95]:
# 4.3 Calculate year and month columns
EPA_air_group['Date']=pd.to_datetime(EPA_air_group['Date'])

EPA_air_group=(
    EPA_air_group
    .assign(
        Year= lambda df:df['Date'].dt.year,
        Month= lambda df:df['Date'].dt.month
    )
)
EPA_air_group.head()

,Date,Local Site Name,AQS Parameter Description,County,mean_aqi,mean_latitude,mean_longitude,Year,Month
0,2024-01-01,Garinger High School,Ozone,Mecklenburg,28.0,35.240100,-80.785683,2024,1
1,2024-01-01,Millbrook School,Ozone,Wake,25.0,35.856111,-78.574167,2024,1
2,2024-01-01,Rockwell,Ozone,Rowan,27.0,35.551868,-80.395039,2024,1
3,2024-01-02,Garinger High School,Ozone,Mecklenburg,23.0,35.240100,-80.785683,2024,1
4,2024-01-02,Millbrook School,Ozone,Wake,23.0,35.856111,-78.574167,2024,1

#### ✅ 4.4 Spread AQI values into separate columns: OZone & PM2.5
* Reshape our table so that Daily AQI values for Ozone and PM2.5 data appear in separate columns.
* Reset the index of the reshaped table to restore it as a flat dataframe.
* Display the first 5 records in the resulting dataframe

In [102]:
# 4.4 Spread data so Ozone, PM2.5 daily AQI valiues occupy separate columns
EPA_air_wide=( 
    EPA_air_group.pivot_table(
        index=['Date', 'Local Site Name', 'County', 'Year', 'Month', 'mean_latitude', 'mean_longitude'],
        columns='AQS Parameter Description',
        values = 'mean_aqi'
    )
.reset_index()
)
EPA_air_wide.head()

AQS Parameter Description,Date,Local Site Name,County,Year,Month,mean_latitude,mean_longitude,Ozone,PM2.5
0,2024-01-01,Garinger High School,Mecklenburg,2024,1,35.240100,-80.785683,28.0,NaN
1,2024-01-01,Millbrook School,Wake,2024,1,35.856111,-78.574167,25.0,NaN
2,2024-01-01,Rockwell,Rowan,2024,1,35.551868,-80.395039,27.0,NaN
3,2024-01-02,Garinger High School,Mecklenburg,2024,1,35.240100,-80.785683,23.0,NaN
4,2024-01-02,Millbrook School,Wake,2024,1,35.856111,-78.574167,23.0,NaN

---
## 5. Save your processed dataset

#### ✅ 5.1 Save the spread dataset to a file 
* Name the spread data file `EPAair_O3_PM25_NC2425_Processed.csv`
* Save it to your processed data folder
* Do not include the dataframe index in your saved file

In [104]:
# 5.1 Save the file
EPA_air_wide.to_csv(processed_fldr/ 'EPAair_O3_PM25_NC2425_Processed.csv', index=False)

---
## 6. Summarize and explore the data

#### ✅ 6.1 Generate a month summary table
* Group the above table to compute mean Ozone and PM2.5 values for each unique site, month, year combination. Be sure to reset the index of the product. 
* Display the first 5 records of this table.

In [109]:
# 6.1 Generate a summary table and show its first 5 records
EPA_air_month_summary = (
    EPA_air_wide
    .groupby(['Local Site Name', 'Year', 'Month'])
    .agg(
        mean_ozone=('Ozone', 'mean'),
        mean_pm25=('PM2.5', 'mean')
    )
    .reset_index()
)
EPA_air_month_summary.head()

  Local Site Name  Year  Month  mean_ozone  mean_pm25
0     Bryson City  2024      3   40.709677        NaN
1     Bryson City  2024      4   43.793103        NaN
2     Bryson City  2024      5   37.419355        NaN
3     Bryson City  2024      6   38.833333        NaN
4     Bryson City  2024      7   31.516129        NaN

---
## 7. Submission
- Save, stage, and commit this notebook
- Push changes to your GitHub account
- Export as an HTML document
- Submit both your `.ipynb` and `.html` document to Canvas.